# Generated by Django 4.2.29 on 2026-03-30 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('text', 'Text vs Text'), ('web', 'Text vs Web'), ('file', 'File vs Web')], default='text', max_length=10)),
                ('original_text', models.TextField()),
                ('compare_text', models.TextField(blank=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('similarity_percentage', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('clean', 'Clean'), ('low', 'Low Plagiarism'), ('medium', 'Medium Plagiarism'), ('high', 'High Plagiarism')], default='clean', max_length=10)),
                ('plagiarism_detected', models.BooleanField(default=False)),
                ('matched_sentences', models.JSONField(default=list)),
                ('source_results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
